apiVersion: v1
kind: ConfigMap
metadata:
  name: {{ include "jira-software.fullname" . }}-cm
  labels:
    {{- include "jira-software.labels" . | nindent 4 }}
data:
  {{- range $key, $val := .Values.envVars }}
  {{ $key }}: {{ $val | quote }}
  {{- end }}
  ATL_JDBC_URL: "{{ .Values.databaseConnection.urlPrefix }}://{{ .Values.databaseConnection.host }}:{{ .Values.databaseConnection.port }}/{{ .Values.databaseConnection.database }}"
  ATL_JDBC_USER: "{{ .Values.databaseConnection.user }}"
  ATL_DB_DRIVER: "{{ .Values.databaseConnection.databaseDriver }}"
  ATL_DB_TYPE: "{{ .Values.databaseConnection.type }}"
  ATL_DB_SCHEMA_NAME: "{{ .Values.databaseConnection.schemaName }}"
  {{- if .Values.ingress.enabled }}
    {{- if not .Values.envVars.ATL_PROXY_NAME }}
  ATL_PROXY_NAME: {{ (index .Values.ingress.hosts 0).host | quote }}
    {{- end }}
    {{- if not .Values.envVars.ATL_PROXY_PORT }}
  ATL_PROXY_PORT: {{ if .Values.ingress.tls }}"443"{{ else }}"80"{{ end }}
    {{- end }}
    {{- if not .Values.envVars.ATL_TOMCAT_SCHEME }}
  ATL_TOMCAT_SCHEME: {{ if .Values.ingress.tls }}"https"{{ else }}"http"{{ end }}
    {{- end }}
    {{- if not .Values.envVars.ATL_TOMCAT_SECURE }}
  ATL_TOMCAT_SECURE: {{ if .Values.ingress.tls }}"true"{{ else }}"false"{{ end }}
    {{- end }}
  {{- end }}
