name: Automerge bot PRs
on:
  pull_request:
    types: [labeled]
jobs:
  automerge:
    runs-on: ubuntu-latest
    steps:
      - name: automerge
        uses: "moxbot/automerge-action@4536e8847eb62fe2f0ee52c8fa92d17aa97f932f"
        env:
          GITHUB_TOKEN: ${{ secrets.PAT_ACCESS }}
          MERGE_FILTER_AUTHOR: "moxbot"
          MERGE_LABELS: "update-appVersion"
          MERGE_COMMIT_MESSAGE: "[Release] Updated to latest stable Apps versions"
          UPDATE_LABELS: "update-appVersion"
